---

- name: Test the wsgi_app_container role
  hosts: rockabox.local
  sudo: yes
  sudo_user: root
  vars_files:
    - defaults/main.yml
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
