---

- name: Create the virtualenv
  command: virtualenv {{ wsgi_virtualenv }} --no-site-packages
           creates={{ wsgi_virtualenv }}bin/activate

- name: Create the Gunicorn script file
  template: src=gunicorn_start.j2
            dest={{ wsgi_virtualenv }}bin/gunicorn_start
            owner={{ wsgi_gunicorn_user }}
            group={{ wsgi_gunicorn_group }}
            mode=0755
            backup=yes

- name: Create the virtualenv postactivate script to set environment variables
  template: src=virtualenv_postactivate.j2
            dest={{ wsgi_virtualenv }}bin/postactivate
            owner={{ wsgi_gunicorn_user }}
            group={{ wsgi_gunicorn_group }}
            mode=0640
            backup=yes
  tags:
    - env_vars
